In [23]:
# Temperature Change Analysis Project

In [24]:
import pandas as pd
import numpy as np

In [25]:
fn_1 = 'FAOSTAT_data_11-24-2020.csv'
fn_2 = 'Environment_Temperature_change_E_All_Data_NOFLAG.csv'

In [26]:
data_fao = pd.read_csv(fn_1)
data_env = pd.read_csv(fn_2)

In [27]:
df_fao = pd.DataFrame()
df_env = pd.DataFrame()

In [28]:
data_env.head()

,Area Code,Area,Months Code,Months,Element Code,Element,Y1961,Y1962,Y1963,Y1964,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,2,Afghanistan,7001,January,7271,Temperature change,0.777,0.062,2.744,-5.232,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
1,2,Afghanistan,7001,January,6078,Standard Deviation,1.950,1.950,1.950,1.950,...,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950
2,2,Afghanistan,7002,February,7271,Temperature change,-1.743,2.465,3.919,-0.202,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
3,2,Afghanistan,7002,February,6078,Standard Deviation,2.597,2.597,2.597,2.597,...,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597
4,2,Afghanistan,7003,March,7271,Temperature change,0.516,1.336,0.403,1.659,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234

In [29]:
df_env_drop = ['Area Code','Months Code','Element Code']

In [32]:
df_env.drop('Area Code',axis=1)

KeyError: "['Area Code'] not found in axis"